"""Added to Recipe user_id

Revision ID: 60be0cd8dbc8
Revises: afca637bb849
Create Date: 2024-04-28 12:36:31.109003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60be0cd8dbc8'
down_revision: Union[str, None] = 'afca637bb849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'user_id')
    # ### end Alembic commands ###
